# Build settings
markdown: kramdown
highlighter: rouge

# Gems
gems: [jekyll-paginate]

# Site settings
title: "Heitor Tashiro Sergent"
description: > # this means to ignore newlines until "email:"
   Coffee, development, burgers, community, psychology. Stuff.

email: heitortsergent@gmail.com
twitter: &twitter https://twitter.com/heitorburger
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Heitor Tashiro Sergent'
author: 'Heitor Tashiro Sergent'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://heitor.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	*twitter
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    
  - icon:	github
    url:	https://github.com/heitortsergent
    desc:	Fork me on github
    share_url:
    share_title:
    share_link: